Datenstrukturen, Algorithmen und Komplexitätstheorie
====================================================

// TODO: Termine abstimmen

. 22. 11. Algorithm - the Basics
. 29. 11. Repräsentation von Daten
. 6. 12.  Statische Datentypen und Datenstrukturen
. 13. 12. Mensch-Maschine-Interaktion, Betriebssysteme
. 20. 12. Dynamische Datentypen
. 27. 12. Sortierungs- und Suchmethoden	(no go)
. 3. 1. Transformationen von Daten		(no go)
. 10. 1. Daten als Kommunikationsmittel
. 17. 1. Parallele Algorithmen
. 24. 1. Brute Force Methods
31. 1.
7. 2.
14. 2.
21. 2.
28. 2.


// VL02

Data Representation
-------------------

. Memory organization
. Elementary number types
. Data endianity
. Boolean logic
. The integer
. Binary and hexadecimal radix, conversions
. The real, float, single, double, and co.



Static Data Types And Structures
--------------------------------

. The structure
. Memory alignment
. Static strings
. Programming with strings



Operating Systems and Interaction Methods
-----------------------------------------

. Operating system structure
. Memory management
. Task scheduling
. Input processing, polling, spin lock
. Event based environment



Dynamic Data Types
------------------

. List
. Hash
. File



Search and Sort
---------------

. Binary trees
. Distributed hash tables
. Bubble sort
. Insertion sort
. Merge sort
. Quick sort



Data Transformations
--------------------

. Compression types
. Simple compression and decompression


Data Transport
--------------

. Structure serialization and deserialization
. XML, JSON, ASN.1


Parallel Algorithms
-------------------

. The Dining Philosophers Problem
. Synchronization Primitives


Brute Force Methods
-------------------

. Monte Carlo
. Genetic Algorithms
