Datenstrukturen, Algorithmen und Komplexitätstheorie
====================================================

. Algorithm - the Basics
. Repräsentation von Daten
. Statische Datentypen und Datenstrukturen
. Mensch-Maschine-Interaktion, Betriebssysteme
. Dynamische Datentypen
. Sortierungs- und Suchmethoden
. Transformationen von Daten
. Daten als Kommunikationsmittel
. Parallele Algorithmen
. Brute Force Methods


// VL02

Data Representation
-------------------

. Memory organization
. Elementary number types
. Data endianity
. Boolean logic
. The integer
. Binary and hexadecimal radix, conversions
. The real, float, single, double, and co.



Static Data Types And Structures
--------------------------------

. The structure
. Memory alignment
. Static strings
. Programming with strings



Operating Systems and Interaction Methods
-----------------------------------------

. Operating system structure
. Memory management
. Task scheduling
. Input processing, polling, spin lock
. Event based environment



Dynamic Data Types
------------------

. List
. Hash
. File



Search and Sort
---------------

. Binary trees
. Distributed hash tables
. Bubble sort
. Insertion sort
. Merge sort
. Quick sort



Data Transformations
--------------------

. Compression types
. Simple compression and decompression


Data Transport
--------------

. Structure serialization and deserialization
. XML, JSON, ASN.1


Parallel Algorithms
-------------------

. The Dining Philosophers Problem
. Synchronization Primitives


Brute Force Methods
-------------------

. Monte Carlo
. Genetic Algorithms
